### ISSUE TITLE
Test model eos24ci in CLI and Colab

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos24ci#2]

**Comment by carcablop** [comment]
Hi @GemmaTuron :
**The model eos24ci fetched successfully! in CLI:**
**Log fetch:** 
[eos24ci_fetch_log.log](https://github.com/ersilia-os/eos24ci/files/10447536/eos24ci_fetch_log.log)
**Output of the input file "eml_canonical.csv":**
[eos24ci.csv](https://github.com/ersilia-os/eos24ci/files/10447592/eos24ci.csv)

When I run the predictions, two .csv files were created with names testing and testing_access and each one with values of SMILES and taxonomy. I attach the files:
[testing.csv](https://github.com/ersilia-os/eos24ci/files/10447624/testing.csv)
[testing_assess.csv](https://github.com/ersilia-os/eos24ci/files/10447626/testing_assess.csv)

**The model eos24c fetched successfully in Colab:**
[log_fetch_colab_eos24ci.txt](https://github.com/ersilia-os/eos24ci/files/10447896/log_fetch_colab_eos24ci.txt)

**Output in Colab:** 
[eos24ci_output.csv](https://github.com/ersilia-os/eos24ci/files/10447976/eos24ci_output.csv)

**Comment by pauline-banye** [comment]
Hi @GemmaTuron, I have succeeded in testing this model.

### Test on CLI
- [ ] I initially received an error  relating to the drugtax module
```
Detailed error:
Model API eos24ci:predict did not produce an outputTraceback (most recent call last):
  File "/root/eos/repository/eos24ci/20230118142426_C5F1DE/eos24ci/artifacts/framework/code/main.py", line 3, in <module>
    import drugtax
ModuleNotFoundError: No module named 'drugtax'

```
[eos24ci_fetch1.log](https://github.com/ersilia-os/eos24ci/files/10447835/eos24ci_fetch1.log)
- [x] To resolve this, I ran the command `pip install drugtax`
- [x] Model fetched, served and predicted successfully on the CLI
[eos24ci_fetch.log](https://github.com/ersilia-os/eos24ci/files/10447833/eos24ci_fetch.log)
- [x] Model predicted successfully with a single smile string
`ersilia -v api predict -i CCCCC -o eos24ci_predict1.csv`
[eos24ci_predict1.csv](https://github.com/ersilia-os/eos24ci/files/10447850/eos24ci_predict1.csv)
- [x] Model predicted successfully with a csv
`ersilia -v api predict -i eml_canonical.csv -o eos24ci_predict.csv`
[eos24ci_predict.csv](https://github.com/ersilia-os/eos24ci/files/10447857/eos24ci_predict.csv)

### Test with colab

- [x] Model fetched, served and predicted successfully on colab
[eos24ci_output.csv](https://github.com/ersilia-os/eos24ci/files/10448177/eos24ci_output.csv)

https://colab.research.google.com/drive/1wkC4IWaGVS7CZGpZlI6exGYaekcgv7Sh?usp=sharing

**Comment by GemmaTuron** [comment]
Wonderful, we will mark this as complete and the model definitely incorporated in the Hub
