### ISSUE TITLE
Test Model eos24ci

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos24ci#3]
Hi,

Please test this model in your CLI and Google Colab @carcablop and @karthikjetty !

**Comment by carcablop** [comment]
Hi @GemmaTuron 

The model run in the Cli sucessfully :
Log fetch: [eos24ci_log.log](https://github.com/ersilia-os/eos24ci/files/10495004/eos24ci_log.log)
output: [eos24ci_predict.csv](https://github.com/ersilia-os/eos24ci/files/10495007/eos24ci_predict.csv)

The model run in Google Colab successfully:

Log_fetch: [log_fetch_googlecolab_eos24ci.txt](https://github.com/ersilia-os/eos24ci/files/10495019/log_fetch_googlecolab_eos24ci.txt)

output: [eos24ci_output(1).csv](https://github.com/ersilia-os/eos24ci/files/10495018/eos24ci_output.1.csv)

**Comment by karthikjetty** [comment]
Model ran on CLI successfully:  [eos24ci.log](https://github.com/ersilia-os/eos24ci/files/10540741/eos24ci.log)

Model also ran successfully on Colab: https://colab.research.google.com/drive/1fSy17sQ1dsOv6OWoRRgpFscGzbwBtW1a#scrollTo=ipckLYxPS3GY
