### ISSUE TITLE
Clean UP & Dockerization eos24ci

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos24ci#4]

**Comment by febielin** [comment]
I have to troubleshoot this model before I start the reformatting. I cannot get this model to work on colab, CLI, or codespaces.

**Comment by GemmaTuron** [comment]
Hi @febielin 
The segmentation fault again: 
`/var/folders/mx/mxb7172x3czgb85qcdk0k1dw0000gn/T/ersilia-k1iabm39/script.sh: line 9: 85263 Segmentation fault: 11  python pack.py`

Could you get the error log from codespaces? it might be the error lies somewhere else as well and this segmentation fault is mac related

**Comment by febielin** [comment]
Hi @GemmaTuron,

Here is the error log: [eos24ci_codespaces.log](https://github.com/ersilia-os/eos24ci/files/11951592/eos24ci_codespaces.log)

Yes, very likely the segmentation fault is Mac related. The error I get on codespaces involves the rdkit package. I will look into this more.

**Comment by GemmaTuron** [comment]
Hi @febielin 
Please add the error here so we can see as well provide guidance

**Comment by febielin** [comment]
Hi @GemmaTuron,

The error log is already attached! Sorry if that wasn't clear. But here it is again: [eos24ci_codespaces.log](https://github.com/ersilia-os/eos24ci/files/11954400/eos24ci_codespaces.log)

**Comment by GemmaTuron** [comment]
my fault completely for reading the issues directly from Gmail, so sorry
It seems is looking for RdKIT in the incorrect place:
```
Requirement already satisfied: rdkit-pypi in /root/miniconda3/envs/ersilia/lib/python3.10/site-packages (2022.9.5)
Requirement already satisfied: numpy in /root/miniconda3/envs/ersilia/lib/python3.10/site-packages (from rdkit-pypi) (1.25.0)
Requirement already satisfied: Pillow in /root/miniconda3/envs/ersilia/lib/python3.10/site-packages (from rdkit-pypi) (9.5.0)
```
(python 3.10, while some other packages are in py 3.7?)

**Comment by febielin** [comment]
Hi @GemmaTuron,

I will look into this more. That is very strange to me because I am working in a conda environment that is running python 3.7. The Dockerfile, as well, requires 3.7. Not sure where the 3.10 is coming in, is this something that is inherent to codespaces?

**Comment by GemmaTuron** [comment]
maybe redirecting some python path somewhere, which might be difficult to debug. Suggest changing to pip install of rdkit IF the descriptors that the model is using are not RdKIT Descriptors (they change between versions, see: https://github.com/ersilia-os/eos2thm/issues/6)

**Comment by febielin** [comment]
@GemmaTuron 
Okay, I've been going in circles with this, but I just remembered something.

At the beginning of this internship, I had trouble following this [installation guide](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation). I just couldn't get the Ersilia Model Hub installed to my device. Miquel recommend both Riley and me to create our ersilia conda environment with python 3.10 instead of 3.7, as specified in the installation guide ([original post](https://ersilia-workspace.slack.com/archives/C038FBH00F7/p1687198023063789?thread_ts=1687193790.400129&cid=C038FBH00F7)). And finally it worked. 

That may be why I'm getting this significant overlap of 3.7 and 3.10. Is it possible that this is why I run into so many package version conflicts? I don't mean with just this model, but in general with a lot of models?

**Comment by GemmaTuron** [comment]
Hi @febielin !

Regarding Python versions, @miquelduranfrigola will be able to provide more explanation but in short:
- Most of the models were developed pre 2022, meaning not adapted to Mac M1 and M2. Hence the issues you experience are related to each individual model, not the Ersilia install per se
- Ersilia deals automatically with python versions, but models might not have the adequate package versions to run in higher python versions and throw back errors, hopefully solved when we use only docker.
Regarding rdkit:
- Molecules are converted to vectors or embeddings in a multitude of ways.
- You need to look individually at each model, where it converts the SMILES to something else.
- An option would be a quick search in the repo for expressions of the type from `rdkit.Chem import Descriptors`

**Comment by GemmaTuron** [comment]
This model is working
